# Generated by Django 3.1.5 on 2021-01-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('promo_start', models.DateTimeField(auto_now_add=True)),
                ('promo_end', models.DateTimeField()),
            ],
        ),
    ]
